'''
This script is used to parse the xml file generated by flow monitor, such that we can get the throughput, latency, and pkt loss rate of the whole network
'''
import xml.etree.ElementTree as ET
import numpy as np

xmlfile = "/home/yang/ns-3.29/simulationResults/flowTransStats-datacenter.xml";
# create element tree object
tree = ET.parse(xmlfile)
# get root element
root = tree.getroot()

throughputs = []
pktLoss = []
delays = []
# iterate news items
for item in root.findall('FlowStats/Flow'):
    rxBytes = int(item.attrib['rxBytes'])
    timeLastRxPacket = float(item.attrib['timeLastRxPacket'][1:-2])/1e9
    timeFirstTxPacket = float(item.attrib['timeFirstTxPacket'][1:-2])/1e9
    txPackts = int(item.attrib['txPackets'])
    rxPackets = int(item.attrib['rxPackets'])
    lostPackets = int(item.attrib['lostPackets'])
    delaySum = float(item.attrib['delaySum'][1:-2])/1e9

    throughputs.append(rxBytes/(timeLastRxPacket-timeFirstTxPacket));
    pktLoss.append(lostPackets/float(rxPackets+lostPackets));
    if rxPackets > 0:
        delays.append(delaySum/float(rxPackets))

print np.mean(throughputs), np.std(throughputs), np.mean(pktLoss), np.std(pktLoss), np.mean(delays), np.std(delays)
