# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('ofswitch13-custom-switch', ['ofswitch13', 'internet-apps'])
    obj.source = 'ofswitch13-custom-switch.cc'

    obj = bld.create_ns3_program('ofswitch13-external-controller', ['ofswitch13', 'internet-apps', 'tap-bridge'])
    obj.source = 'ofswitch13-external-controller.cc'

    obj = bld.create_ns3_program('ofswitch13-first', ['ofswitch13', 'internet-apps'])
    obj.source = 'ofswitch13-first.cc'

    obj = bld.create_ns3_program('ofswitch13-logical-port', ['ofswitch13', 'internet-apps', 'lte'])
    obj.source = ['ofswitch13-logical-port/main.cc', 'ofswitch13-logical-port/tunnel-controller.cc', 'ofswitch13-logical-port/gtp-tunnel-app.cc']

    obj = bld.create_ns3_program('ofswitch13-multiple-controllers', ['ofswitch13', 'internet-apps'])
    obj.source = 'ofswitch13-multiple-controllers.cc'

    obj = bld.create_ns3_program('ofswitch13-multiple-domains', ['ofswitch13', 'internet-apps'])
    obj.source = 'ofswitch13-multiple-domains.cc'

    obj = bld.create_ns3_program('ofswitch13-qos-controller', ['ofswitch13', 'netanim'])
    obj.source = ['ofswitch13-qos-controller/main.cc', 'ofswitch13-qos-controller/qos-controller.cc']

    obj = bld.create_ns3_program('ofswitch13-single-domain', ['ofswitch13', 'internet-apps'])
    obj.source = 'ofswitch13-single-domain.cc'

    obj = bld.create_ns3_program('ofswitch13-single-switch-externalController', ['ofswitch13', 'internet-apps', 'tap-bridge', 'flow-monitor'])
    obj.source = 'single-switch-externalController.cc'

    obj = bld.create_ns3_program('ofswitch13-datacenter-externalController', ['ofswitch13', 'internet-apps', 'tap-bridge', 'flow-monitor'])
    obj.source = 'datacenter-externalController.cc'

    obj = bld.create_ns3_program('ofswitch13-linear-externalController', ['ofswitch13', 'internet-apps', 'tap-bridge', 'flow-monitor'])
    obj.source = 'linear-externalController.cc'

    obj = bld.create_ns3_program('ofswitch13-linear-externalController-v2', ['ofswitch13', 'internet-apps', 'tap-bridge', 'flow-monitor'])
    obj.source = 'linear-externalController-v2.cc'

    obj = bld.create_ns3_program('ofswitch13-datacenter-dijkstra', ['ofswitch13', 'internet-apps', 'flow-monitor'])
    obj.source = 'datacenter-dijkstra.cc'
